export interface CityData {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  county: string;
  population: string;
  zipCodes: string[];
  nearbyAreas: string[];
  primaryKeyword: string;
  emergencyKeyword: string;
  drainKeyword: string;
  waterHeaterKeyword: string;
  burstPipeKeyword: string;
  pipeRepairKeyword: string;
  avgResponseTime: string;
  heroTagline: string;
  heroSub: string;
  localFact: string;
}

export const CITIES: CityData[] = [
  {
    slug: 'nashville',
    name: 'Nashville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Davidson County',
    population: '700,000+',
    zipCodes: ['37201', '37203', '37205', '37206', '37207', '37208', '37209', '37210', '37211', '37212', '37213', '37214', '37215', '37216', '37217', '37218', '37219', '37220', '37221'],
    nearbyAreas: ['Brentwood', 'Franklin', 'Antioch', 'Bellevue', 'Hermitage', 'Madison'],
    primaryKeyword: 'plumber nashville tn',
    emergencyKeyword: 'emergency plumber nashville',
    drainKeyword: 'drain cleaning nashville tn',
    waterHeaterKeyword: 'water heater installation nashville tn',
    burstPipeKeyword: 'burst pipe repair nashville tn',
    pipeRepairKeyword: 'pipe repair nashville tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Nashville\'s 24/7 Licensed Plumber',
    heroSub: 'Same-Hour Emergency. Upfront Pricing. 1-Year Guarantee.',
    localFact: 'Nashville\'s aging water infrastructure and rapid growth mean plumbing issues are common. Our licensed master plumbers serve all of Davidson County.',
  },
  {
    slug: 'brentwood',
    name: 'Brentwood',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Williamson County',
    population: '45,000',
    zipCodes: ['37027'],
    nearbyAreas: ['Franklin', 'Nashville', 'Nolensville', 'Antioch'],
    primaryKeyword: 'plumber brentwood tn',
    emergencyKeyword: 'emergency plumber brentwood tn',
    drainKeyword: 'drain cleaning brentwood tn',
    waterHeaterKeyword: 'water heater installation brentwood tn',
    burstPipeKeyword: 'burst pipe repair brentwood tn',
    pipeRepairKeyword: 'pipe repair brentwood tn',
    avgResponseTime: '35 minutes',
    heroTagline: 'Brentwood\'s #1 Licensed Plumber',
    heroSub: 'Williamson County\'s Trusted Plumbing Pros. Licensed. Insured. Same-Day.',
    localFact: 'Brentwood\'s premium homes deserve premium plumbing service. We specialize in high-end fixture installation, tankless water heaters, and whole-home repipes for Williamson County\'s finest properties.',
  },
  {
    slug: 'franklin',
    name: 'Franklin',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Williamson County',
    population: '85,000',
    zipCodes: ['37064', '37067', '37069'],
    nearbyAreas: ['Brentwood', 'Spring Hill', 'Thompson\'s Station', 'Nolensville'],
    primaryKeyword: 'plumber franklin tn',
    emergencyKeyword: 'emergency plumber franklin tn',
    drainKeyword: 'drain cleaning franklin tn',
    waterHeaterKeyword: 'water heater installation franklin tn',
    burstPipeKeyword: 'burst pipe repair franklin tn',
    pipeRepairKeyword: 'pipe repair franklin tn',
    avgResponseTime: '40 minutes',
    heroTagline: 'Franklin TN\'s Trusted Plumber',
    heroSub: 'Licensed. Background-Checked. Same-Day Service in Franklin & Williamson County.',
    localFact: 'Franklin is one of the fastest-growing cities in the US. With thousands of new homes and older historic properties, licensed plumbing service is in constant demand across all of Franklin.',
  },
  {
    slug: 'spring-hill',
    name: 'Spring Hill',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Williamson / Maury County',
    population: '50,000',
    zipCodes: ['37174'],
    nearbyAreas: ['Franklin', 'Columbia', 'Thompson\'s Station', 'Nolensville'],
    primaryKeyword: 'plumber spring hill tn',
    emergencyKeyword: 'emergency plumber spring hill tn',
    drainKeyword: 'drain cleaning spring hill tn',
    waterHeaterKeyword: 'water heater installation spring hill tn',
    burstPipeKeyword: 'burst pipe repair spring hill tn',
    pipeRepairKeyword: 'pipe repair spring hill tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Spring Hill TN\'s Licensed Plumber',
    heroSub: 'Fast-Growing Spring Hill Deserves Fast, Reliable Plumbing Service.',
    localFact: 'Spring Hill is the fastest-growing suburb in Tennessee. New construction means new water heater installs, and the area\'s rapid development brings unique plumbing demands that our licensed team handles daily.',
  },
  {
    slug: 'murfreesboro',
    name: 'Murfreesboro',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Rutherford County',
    population: '155,000',
    zipCodes: ['37127', '37128', '37129', '37130', '37132'],
    nearbyAreas: ['Nashville', 'Smyrna', 'La Vergne', 'Lavergne', 'Christiana'],
    primaryKeyword: 'plumber murfreesboro tn',
    emergencyKeyword: 'emergency plumber murfreesboro tn',
    drainKeyword: 'drain cleaning murfreesboro tn',
    waterHeaterKeyword: 'water heater installation murfreesboro tn',
    burstPipeKeyword: 'burst pipe repair murfreesboro tn',
    pipeRepairKeyword: 'pipe repair murfreesboro tn',
    avgResponseTime: '50 minutes',
    heroTagline: 'Murfreesboro\'s 24/7 Licensed Plumber',
    heroSub: 'Rutherford County\'s Fastest Plumbing Response. Licensed & Insured.',
    localFact: 'As one of Tennessee\'s largest and fastest-growing cities, Murfreesboro has a mix of new construction and older homes — both need expert plumbing attention. We serve all of Rutherford County.',
  },
  {
    slug: 'mount-juliet',
    name: 'Mount Juliet',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Wilson County',
    population: '40,000',
    zipCodes: ['37122'],
    nearbyAreas: ['Lebanon', 'Hermitage', 'Nashville', 'Donelson'],
    primaryKeyword: 'plumber mount juliet tn',
    emergencyKeyword: 'emergency plumber mount juliet tn',
    drainKeyword: 'drain cleaning mount juliet tn',
    waterHeaterKeyword: 'water heater installation mount juliet tn',
    burstPipeKeyword: 'burst pipe repair mount juliet tn',
    pipeRepairKeyword: 'pipe repair mount juliet tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Mount Juliet TN\'s Trusted Plumber',
    heroSub: 'Wilson County Licensed Plumbers. Same-Day. Upfront Pricing.',
    localFact: 'Mount Juliet\'s growing Wilson County community needs reliable local plumbing. We cover all of the 37122 zip code with same-day availability and transparent pricing.',
  },
  {
    slug: 'hendersonville',
    name: 'Hendersonville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Sumner County',
    population: '65,000',
    zipCodes: ['37075', '37077'],
    nearbyAreas: ['Goodlettsville', 'Gallatin', 'Madison', 'Nashville'],
    primaryKeyword: 'plumber hendersonville tn',
    emergencyKeyword: 'emergency plumber hendersonville tn',
    drainKeyword: 'drain cleaning hendersonville tn',
    waterHeaterKeyword: 'water heater installation hendersonville tn',
    burstPipeKeyword: 'burst pipe repair hendersonville tn',
    pipeRepairKeyword: 'pipe repair hendersonville tn',
    avgResponseTime: '40 minutes',
    heroTagline: 'Hendersonville TN\'s Licensed Plumber',
    heroSub: 'Sumner County\'s Most Trusted Plumbing Team. Available 24/7.',
    localFact: 'Hendersonville is one of Sumner County\'s most established communities. With many homes built in the 1980s and 90s now needing pipe and water heater upgrades, our licensed team is the go-to choice.',
  },
  // ── Phase 2: Nashville Metro Expansion ──────────────────────────────────
  {
    slug: 'clarksville',
    name: 'Clarksville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Montgomery County',
    population: '170,000',
    zipCodes: ['37040', '37041', '37042', '37043', '37044'],
    nearbyAreas: ['Nashville', 'Oak Grove', 'Pleasant View', 'Hopkinsville'],
    primaryKeyword: 'plumber clarksville tn',
    emergencyKeyword: 'emergency plumber clarksville tn',
    drainKeyword: 'drain cleaning clarksville tn',
    waterHeaterKeyword: 'water heater installation clarksville tn',
    burstPipeKeyword: 'burst pipe repair clarksville tn',
    pipeRepairKeyword: 'pipe repair clarksville tn',
    avgResponseTime: '55 minutes',
    heroTagline: 'Clarksville TN\'s 24/7 Licensed Plumber',
    heroSub: 'Military Families Trust Us. Licensed, Insured & Background-Checked.',
    localFact: 'Clarksville is home to over 40,000 military families stationed at Fort Campbell. We understand the demands of military life and provide fast, no-hassle plumbing service throughout all of Montgomery County — day or night.',
  },
  {
    slug: 'nolensville',
    name: 'Nolensville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Williamson County',
    population: '15,000',
    zipCodes: ['37135'],
    nearbyAreas: ['Brentwood', 'Franklin', 'Spring Hill', 'Nashville'],
    primaryKeyword: 'plumber nolensville tn',
    emergencyKeyword: 'emergency plumber nolensville tn',
    drainKeyword: 'drain cleaning nolensville tn',
    waterHeaterKeyword: 'water heater installation nolensville tn',
    burstPipeKeyword: 'burst pipe repair nolensville tn',
    pipeRepairKeyword: 'pipe repair nolensville tn',
    avgResponseTime: '35 minutes',
    heroTagline: 'Nolensville TN\'s Licensed Plumber',
    heroSub: 'High-Income Williamson County Community. Same-Day Licensed Service.',
    localFact: 'Nolensville is one of Tennessee\'s fastest-growing and highest-income communities, with average household incomes exceeding $145K. New construction is booming and our licensed plumbers handle water heater installs and pipe work for new and existing homes throughout Williamson County.',
  },
  {
    slug: 'gallatin',
    name: 'Gallatin',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Sumner County',
    population: '40,000',
    zipCodes: ['37066'],
    nearbyAreas: ['Hendersonville', 'Nashville', 'Goodlettsville', 'Portland'],
    primaryKeyword: 'plumber gallatin tn',
    emergencyKeyword: 'emergency plumber gallatin tn',
    drainKeyword: 'drain cleaning gallatin tn',
    waterHeaterKeyword: 'water heater installation gallatin tn',
    burstPipeKeyword: 'burst pipe repair gallatin tn',
    pipeRepairKeyword: 'pipe repair gallatin tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Gallatin TN\'s Trusted Plumber',
    heroSub: 'Sumner County\'s Reliable Plumbing Team. Available Day & Night.',
    localFact: 'Gallatin is the county seat of Sumner County and a growing suburb northeast of Nashville. Many older homes in Gallatin are due for pipe upgrades, while newer subdivisions need water heater installs and routine maintenance — our licensed team handles both.',
  },
  {
    slug: 'lebanon',
    name: 'Lebanon',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Wilson County',
    population: '35,000',
    zipCodes: ['37087', '37090'],
    nearbyAreas: ['Mount Juliet', 'Nashville', 'Carthage', 'Watertown'],
    primaryKeyword: 'plumber lebanon tn',
    emergencyKeyword: 'emergency plumber lebanon tn',
    drainKeyword: 'drain cleaning lebanon tn',
    waterHeaterKeyword: 'water heater installation lebanon tn',
    burstPipeKeyword: 'burst pipe repair lebanon tn',
    pipeRepairKeyword: 'pipe repair lebanon tn',
    avgResponseTime: '50 minutes',
    heroTagline: 'Lebanon TN\'s Licensed Plumber',
    heroSub: 'Wilson County Plumbing Pros. Licensed & Same-Day Service.',
    localFact: 'Lebanon is the county seat of Wilson County and has seen strong growth as a Nashville suburb. The mix of historic downtown properties and newer subdivisions creates diverse plumbing needs that our licensed team handles daily.',
  },
  {
    slug: 'germantown',
    name: 'Germantown',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Shelby County',
    population: '40,000',
    zipCodes: ['38138', '38139'],
    nearbyAreas: ['Memphis', 'Collierville', 'Bartlett', 'Cordova'],
    primaryKeyword: 'plumber germantown tn',
    emergencyKeyword: 'emergency plumber germantown tn',
    drainKeyword: 'drain cleaning germantown tn',
    waterHeaterKeyword: 'water heater installation germantown tn',
    burstPipeKeyword: 'burst pipe repair germantown tn',
    pipeRepairKeyword: 'pipe repair germantown tn',
    avgResponseTime: '35 minutes',
    heroTagline: 'Germantown TN\'s #1 Licensed Plumber',
    heroSub: 'Shelby County\'s Premier Plumbing Service. Licensed, Insured, Same-Day.',
    localFact: 'Germantown is one of Tennessee\'s most affluent communities with average household incomes over $140K. Our licensed plumbers specialize in high-end fixture installation, whole-home repipes, and tankless water heater upgrades for Germantown\'s premier properties.',
  },
  {
    slug: 'collierville',
    name: 'Collierville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Shelby County',
    population: '50,000',
    zipCodes: ['38017'],
    nearbyAreas: ['Germantown', 'Memphis', 'Bartlett', 'Arlington'],
    primaryKeyword: 'plumber collierville tn',
    emergencyKeyword: 'emergency plumber collierville tn',
    drainKeyword: 'drain cleaning collierville tn',
    waterHeaterKeyword: 'water heater installation collierville tn',
    burstPipeKeyword: 'burst pipe repair collierville tn',
    pipeRepairKeyword: 'pipe repair collierville tn',
    avgResponseTime: '40 minutes',
    heroTagline: 'Collierville TN\'s Licensed Plumber',
    heroSub: 'West Tennessee\'s Most Trusted Plumbing Team. Available 24/7.',
    localFact: 'Collierville is one of the fastest-growing and highest-income suburbs in the Memphis area. New home construction is constant and our licensed plumbers are in high demand for water heater installations, drain cleaning, and emergency plumbing throughout Shelby County.',
  },
  {
    slug: 'smyrna',
    name: 'Smyrna',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Rutherford County',
    population: '60,000',
    zipCodes: ['37167'],
    nearbyAreas: ['Murfreesboro', 'La Vergne', 'Nashville', 'Antioch'],
    primaryKeyword: 'plumber smyrna tn',
    emergencyKeyword: 'emergency plumber smyrna tn',
    drainKeyword: 'drain cleaning smyrna tn',
    waterHeaterKeyword: 'water heater installation smyrna tn',
    burstPipeKeyword: 'burst pipe repair smyrna tn',
    pipeRepairKeyword: 'pipe repair smyrna tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Smyrna TN\'s Trusted Plumber',
    heroSub: 'Rutherford County Plumbing Experts. Licensed. Same-Day.',
    localFact: 'Smyrna is home to the massive Nissan manufacturing plant and has grown rapidly as a result. The combination of industrial and residential growth means constant demand for licensed plumbing across the 37167 zip code.',
  },
  {
    slug: 'columbia',
    name: 'Columbia',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Maury County',
    population: '45,000',
    zipCodes: ['38401', '38402'],
    nearbyAreas: ['Spring Hill', 'Franklin', 'Mount Pleasant', 'Lewisburg'],
    primaryKeyword: 'plumber columbia tn',
    emergencyKeyword: 'emergency plumber columbia tn',
    drainKeyword: 'drain cleaning columbia tn',
    waterHeaterKeyword: 'water heater installation columbia tn',
    burstPipeKeyword: 'burst pipe repair columbia tn',
    pipeRepairKeyword: 'pipe repair columbia tn',
    avgResponseTime: '55 minutes',
    heroTagline: 'Columbia TN\'s Licensed Plumber',
    heroSub: 'Maury County\'s Most Reliable Plumbing Service. Available 24/7.',
    localFact: 'Columbia is the county seat of Maury County and a growing hub in the Spring Hill corridor. With an influx of new residents and businesses, our licensed plumbers are ready for everything from emergency plumbing to whole-home water heater replacements throughout Maury County.',
  },
  // ── Phase 3: East TN + More Memphis ─────────────────────────────────────
  {
    slug: 'knoxville',
    name: 'Knoxville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Knox County',
    population: '190,000',
    zipCodes: ['37902', '37909', '37912', '37914', '37916', '37917', '37918', '37919', '37920', '37921', '37922', '37923', '37924'],
    nearbyAreas: ['Farragut', 'Maryville', 'Oak Ridge', 'Lenoir City'],
    primaryKeyword: 'plumber knoxville tn',
    emergencyKeyword: 'emergency plumber knoxville tn',
    drainKeyword: 'drain cleaning knoxville tn',
    waterHeaterKeyword: 'water heater installation knoxville tn',
    burstPipeKeyword: 'burst pipe repair knoxville tn',
    pipeRepairKeyword: 'pipe repair knoxville tn',
    avgResponseTime: '50 minutes',
    heroTagline: 'Knoxville TN\'s 24/7 Licensed Plumber',
    heroSub: 'Knox County\'s Most Trusted Plumbing Team. Same-Day. Licensed. Insured.',
    localFact: 'Knoxville is East Tennessee\'s largest city and home to the University of Tennessee. With a mix of historic neighborhoods, student housing, and growing suburbs, licensed plumbing demand is high year-round. Cold winters mean burst pipe emergencies are common across Knox County.',
  },
  {
    slug: 'farragut',
    name: 'Farragut',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Knox County',
    population: '23,000',
    zipCodes: ['37934'],
    nearbyAreas: ['Knoxville', 'Lenoir City', 'Oak Ridge', 'Loudon'],
    primaryKeyword: 'plumber farragut tn',
    emergencyKeyword: 'emergency plumber farragut tn',
    drainKeyword: 'drain cleaning farragut tn',
    waterHeaterKeyword: 'water heater installation farragut tn',
    burstPipeKeyword: 'burst pipe repair farragut tn',
    pipeRepairKeyword: 'pipe repair farragut tn',
    avgResponseTime: '40 minutes',
    heroTagline: 'Farragut TN\'s #1 Licensed Plumber',
    heroSub: 'Knox County\'s Highest-Income Community Deserves the Best Plumbing Service.',
    localFact: 'Farragut consistently ranks as one of Tennessee\'s wealthiest communities with average household incomes exceeding $120K. Luxury homes here demand premium plumbing service — tankless water heaters, whole-home repipes, and high-end fixture installations are our specialty.',
  },
  {
    slug: 'chattanooga',
    name: 'Chattanooga',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Hamilton County',
    population: '180,000',
    zipCodes: ['37401', '37402', '37403', '37404', '37405', '37406', '37407', '37408', '37409', '37410', '37411', '37412', '37415', '37416', '37421'],
    nearbyAreas: ['Hixson', 'Collegedale', 'East Ridge', 'Cleveland'],
    primaryKeyword: 'plumber chattanooga tn',
    emergencyKeyword: 'emergency plumber chattanooga tn',
    drainKeyword: 'drain cleaning chattanooga tn',
    waterHeaterKeyword: 'water heater installation chattanooga tn',
    burstPipeKeyword: 'burst pipe repair chattanooga tn',
    pipeRepairKeyword: 'pipe repair chattanooga tn',
    avgResponseTime: '55 minutes',
    heroTagline: 'Chattanooga TN\'s 24/7 Licensed Plumber',
    heroSub: 'Hamilton County Plumbing Pros. Emergency Service Around the Clock.',
    localFact: 'Chattanooga is one of Tennessee\'s fastest-growing cities with booming downtown development and an influx of new residents. From historic Southside homes to brand-new North Shore apartments, our licensed plumbers cover all of Hamilton County.',
  },
  {
    slug: 'bartlett',
    name: 'Bartlett',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Shelby County',
    population: '55,000',
    zipCodes: ['38002', '38135'],
    nearbyAreas: ['Memphis', 'Germantown', 'Millington', 'Arlington'],
    primaryKeyword: 'plumber bartlett tn',
    emergencyKeyword: 'emergency plumber bartlett tn',
    drainKeyword: 'drain cleaning bartlett tn',
    waterHeaterKeyword: 'water heater installation bartlett tn',
    burstPipeKeyword: 'burst pipe repair bartlett tn',
    pipeRepairKeyword: 'pipe repair bartlett tn',
    avgResponseTime: '35 minutes',
    heroTagline: 'Bartlett TN\'s Licensed Plumber',
    heroSub: 'Northeast Memphis Suburb\'s Most Trusted Plumbing Team. Same-Day Service.',
    localFact: 'Bartlett is one of the largest Memphis suburbs with a well-established residential community. Homes built in the 1980s and 90s are now reaching the age when water heaters, supply lines, and main pipes need replacement — and our licensed team is ready.',
  },
  {
    slug: 'arlington',
    name: 'Arlington',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Shelby County',
    population: '12,000',
    zipCodes: ['38002'],
    nearbyAreas: ['Bartlett', 'Germantown', 'Collierville', 'Lakeland'],
    primaryKeyword: 'plumber arlington tn',
    emergencyKeyword: 'emergency plumber arlington tn',
    drainKeyword: 'drain cleaning arlington tn',
    waterHeaterKeyword: 'water heater installation arlington tn',
    burstPipeKeyword: 'burst pipe repair arlington tn',
    pipeRepairKeyword: 'pipe repair arlington tn',
    avgResponseTime: '40 minutes',
    heroTagline: 'Arlington TN\'s Licensed Plumber',
    heroSub: 'Shelby County\'s Fastest-Growing Small Town. Reliable Same-Day Plumbing.',
    localFact: 'Arlington is one of the fastest-growing communities in Shelby County, attracting young families with its top-rated schools and newer homes. New construction means high demand for water heater installs and whole-home plumbing services.',
  },
  {
    slug: 'lakeland',
    name: 'Lakeland',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Shelby County',
    population: '14,000',
    zipCodes: ['38002'],
    nearbyAreas: ['Bartlett', 'Arlington', 'Germantown', 'Memphis'],
    primaryKeyword: 'plumber lakeland tn',
    emergencyKeyword: 'emergency plumber lakeland tn',
    drainKeyword: 'drain cleaning lakeland tn',
    waterHeaterKeyword: 'water heater installation lakeland tn',
    burstPipeKeyword: 'burst pipe repair lakeland tn',
    pipeRepairKeyword: 'pipe repair lakeland tn',
    avgResponseTime: '35 minutes',
    heroTagline: 'Lakeland TN\'s Licensed Plumber',
    heroSub: 'Shelby County\'s Premier Growing Community. Licensed Plumbing Pros.',
    localFact: 'Lakeland is a fast-growing, family-oriented community in northeast Shelby County. With a high concentration of newer homes and young families, our licensed plumbers specialize in new construction plumbing, water heater installations, and routine maintenance.',
  },
  {
    slug: 'maryville',
    name: 'Maryville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Blount County',
    population: '30,000',
    zipCodes: ['37801', '37803'],
    nearbyAreas: ['Knoxville', 'Alcoa', 'Farragut', 'Friendsville'],
    primaryKeyword: 'plumber maryville tn',
    emergencyKeyword: 'emergency plumber maryville tn',
    drainKeyword: 'drain cleaning maryville tn',
    waterHeaterKeyword: 'water heater installation maryville tn',
    burstPipeKeyword: 'burst pipe repair maryville tn',
    pipeRepairKeyword: 'pipe repair maryville tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Maryville TN\'s Licensed Plumber',
    heroSub: 'Blount County\'s Trusted Plumbing Team. Available 24/7 for Emergencies.',
    localFact: 'Maryville is the county seat of Blount County and a charming bedroom community to Knoxville. The city\'s mix of older homes near downtown and newer subdivisions in surrounding areas creates steady plumbing demand across Blount County.',
  },
  {
    slug: 'oak-ridge',
    name: 'Oak Ridge',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Anderson County',
    population: '31,000',
    zipCodes: ['37830', '37831'],
    nearbyAreas: ['Knoxville', 'Farragut', 'Clinton', 'Kingston'],
    primaryKeyword: 'plumber oak ridge tn',
    emergencyKeyword: 'emergency plumber oak ridge tn',
    drainKeyword: 'drain cleaning oak ridge tn',
    waterHeaterKeyword: 'water heater installation oak ridge tn',
    burstPipeKeyword: 'burst pipe repair oak ridge tn',
    pipeRepairKeyword: 'pipe repair oak ridge tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Oak Ridge TN\'s Licensed Plumber',
    heroSub: 'Anderson County\'s Reliable Plumbing Experts. Stable Workforce, Trusted Service.',
    localFact: 'Oak Ridge is home to a large government and research workforce, creating a stable community with consistent plumbing needs. Many homes built in the 1950s and 60s now need pipe upgrades, water heater replacements, and comprehensive plumbing updates.',
  },
  {
    slug: 'cleveland',
    name: 'Cleveland',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Bradley County',
    population: '45,000',
    zipCodes: ['37311', '37312'],
    nearbyAreas: ['Chattanooga', 'Knoxville', 'Athens', 'Benton'],
    primaryKeyword: 'plumber cleveland tn',
    emergencyKeyword: 'emergency plumber cleveland tn',
    drainKeyword: 'drain cleaning cleveland tn',
    waterHeaterKeyword: 'water heater installation cleveland tn',
    burstPipeKeyword: 'burst pipe repair cleveland tn',
    pipeRepairKeyword: 'pipe repair cleveland tn',
    avgResponseTime: '50 minutes',
    heroTagline: 'Cleveland TN\'s Licensed Plumber',
    heroSub: 'Bradley County\'s Go-To Plumbing Team. Same-Day Emergency Service.',
    localFact: 'Cleveland sits between Chattanooga and Knoxville, serving as a commercial and industrial hub for Bradley County. With steady population growth and a strong manufacturing base, licensed plumbing services are in constant demand throughout the area.',
  },
  {
    slug: 'cookeville',
    name: 'Cookeville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Putnam County',
    population: '35,000',
    zipCodes: ['38501', '38502', '38503', '38506'],
    nearbyAreas: ['Nashville', 'Knoxville', 'Sparta', 'Crossville'],
    primaryKeyword: 'plumber cookeville tn',
    emergencyKeyword: 'emergency plumber cookeville tn',
    drainKeyword: 'drain cleaning cookeville tn',
    waterHeaterKeyword: 'water heater installation cookeville tn',
    burstPipeKeyword: 'burst pipe repair cookeville tn',
    pipeRepairKeyword: 'pipe repair cookeville tn',
    avgResponseTime: '60 minutes',
    heroTagline: 'Cookeville TN\'s Licensed Plumber',
    heroSub: 'Putnam County Plumbing Pros. Between Nashville & Knoxville — Fully Licensed.',
    localFact: 'Cookeville is the Upper Cumberland region\'s hub and home to Tennessee Tech University. The combination of student housing, older residential neighborhoods, and growing suburbs creates diverse plumbing needs across Putnam County.',
  },
  // ── Phase 4: Full State Coverage ────────────────────────────────────────
  {
    slug: 'la-vergne',
    name: 'La Vergne',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Rutherford County',
    population: '35,000',
    zipCodes: ['37086'],
    nearbyAreas: ['Smyrna', 'Murfreesboro', 'Antioch', 'Nashville'],
    primaryKeyword: 'plumber la vergne tn',
    emergencyKeyword: 'emergency plumber la vergne tn',
    drainKeyword: 'drain cleaning la vergne tn',
    waterHeaterKeyword: 'water heater installation la vergne tn',
    burstPipeKeyword: 'burst pipe repair la vergne tn',
    pipeRepairKeyword: 'pipe repair la vergne tn',
    avgResponseTime: '40 minutes',
    heroTagline: 'La Vergne TN\'s Licensed Plumber',
    heroSub: 'Rutherford County\'s Affordable Suburb. Fast, Licensed Plumbing Service.',
    localFact: 'La Vergne is one of Tennessee\'s most affordable Nashville suburbs and has grown rapidly with families and businesses. Situated near major logistics hubs, the area\'s mix of residential and commercial properties keeps licensed plumbers busy year-round.',
  },
  {
    slug: 'goodlettsville',
    name: 'Goodlettsville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Davidson / Sumner County',
    population: '17,000',
    zipCodes: ['37072'],
    nearbyAreas: ['Hendersonville', 'Nashville', 'Madison', 'Millersville'],
    primaryKeyword: 'plumber goodlettsville tn',
    emergencyKeyword: 'emergency plumber goodlettsville tn',
    drainKeyword: 'drain cleaning goodlettsville tn',
    waterHeaterKeyword: 'water heater installation goodlettsville tn',
    burstPipeKeyword: 'burst pipe repair goodlettsville tn',
    pipeRepairKeyword: 'pipe repair goodlettsville tn',
    avgResponseTime: '35 minutes',
    heroTagline: 'Goodlettsville TN\'s Licensed Plumber',
    heroSub: 'North Nashville\'s Trusted Plumbing Team. Available Day & Night.',
    localFact: 'Goodlettsville straddles the Davidson and Sumner county line just north of Nashville. Many homes here were built in the 1970s and 80s and are prime candidates for water heater upgrades, supply line replacements, and drain cleaning services.',
  },
  {
    slug: 'thompsons-station',
    name: 'Thompson\'s Station',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Williamson County',
    population: '12,000',
    zipCodes: ['37179'],
    nearbyAreas: ['Spring Hill', 'Franklin', 'Columbia', 'Nolensville'],
    primaryKeyword: 'plumber thompsons station tn',
    emergencyKeyword: 'emergency plumber thompsons station tn',
    drainKeyword: 'drain cleaning thompsons station tn',
    waterHeaterKeyword: 'water heater installation thompsons station tn',
    burstPipeKeyword: 'burst pipe repair thompsons station tn',
    pipeRepairKeyword: 'pipe repair thompsons station tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Thompson\'s Station TN\'s Licensed Plumber',
    heroSub: 'Williamson County\'s Hidden Gem. Same-Day Licensed Plumbing Service.',
    localFact: 'Thompson\'s Station is one of Williamson County\'s most affluent small communities with average household incomes near $140K. New construction is booming here, creating strong demand for water heater installations and whole-home plumbing services.',
  },
  {
    slug: 'memphis',
    name: 'Memphis',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Shelby County',
    population: '633,000',
    zipCodes: ['38103', '38104', '38105', '38106', '38107', '38108', '38109', '38111', '38112', '38114', '38115', '38116', '38117', '38118', '38119', '38120', '38122', '38125', '38127', '38128', '38132', '38133', '38134', '38141'],
    nearbyAreas: ['Germantown', 'Collierville', 'Bartlett', 'Millington'],
    primaryKeyword: 'plumber memphis tn',
    emergencyKeyword: 'emergency plumber memphis tn',
    drainKeyword: 'drain cleaning memphis tn',
    waterHeaterKeyword: 'water heater installation memphis tn',
    burstPipeKeyword: 'burst pipe repair memphis tn',
    pipeRepairKeyword: 'pipe repair memphis tn',
    avgResponseTime: '35 minutes',
    heroTagline: 'Memphis TN\'s 24/7 Licensed Plumber',
    heroSub: 'Shelby County\'s Largest City. Emergency Plumbing Around the Clock.',
    localFact: 'Memphis is Tennessee\'s second-largest city and a major commercial and cultural hub. With a wide mix of older historic homes, apartments, and commercial properties, licensed plumbing demand is constant throughout all 24+ Memphis zip codes we serve.',
  },
  {
    slug: 'kingsport',
    name: 'Kingsport',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Sullivan County',
    population: '55,000',
    zipCodes: ['37660', '37663', '37664', '37665'],
    nearbyAreas: ['Johnson City', 'Bristol', 'Elizabethton', 'Church Hill'],
    primaryKeyword: 'plumber kingsport tn',
    emergencyKeyword: 'emergency plumber kingsport tn',
    drainKeyword: 'drain cleaning kingsport tn',
    waterHeaterKeyword: 'water heater installation kingsport tn',
    burstPipeKeyword: 'burst pipe repair kingsport tn',
    pipeRepairKeyword: 'pipe repair kingsport tn',
    avgResponseTime: '60 minutes',
    heroTagline: 'Kingsport TN\'s Licensed Plumber',
    heroSub: 'Tri-Cities\' Anchor City. Licensed & Insured Plumbing Service.',
    localFact: 'Kingsport is the industrial and commercial anchor of the Tri-Cities region in Northeast Tennessee. With a large industrial workforce and established residential neighborhoods, our licensed plumbers serve homes and businesses throughout Sullivan County.',
  },
  {
    slug: 'johnson-city',
    name: 'Johnson City',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Washington County',
    population: '67,000',
    zipCodes: ['37601', '37604'],
    nearbyAreas: ['Kingsport', 'Bristol', 'Elizabethton', 'Erwin'],
    primaryKeyword: 'plumber johnson city tn',
    emergencyKeyword: 'emergency plumber johnson city tn',
    drainKeyword: 'drain cleaning johnson city tn',
    waterHeaterKeyword: 'water heater installation johnson city tn',
    burstPipeKeyword: 'burst pipe repair johnson city tn',
    pipeRepairKeyword: 'pipe repair johnson city tn',
    avgResponseTime: '60 minutes',
    heroTagline: 'Johnson City TN\'s Licensed Plumber',
    heroSub: 'Washington County\'s Most Trusted Plumbing Team. Same-Day Available.',
    localFact: 'Johnson City is home to East Tennessee State University and serves as the healthcare and retail hub of the Tri-Cities region. The large student population, historic neighborhoods, and growing medical corridor create steady plumbing demand throughout Washington County.',
  },
  {
    slug: 'bristol',
    name: 'Bristol',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Sullivan County',
    population: '27,000',
    zipCodes: ['37620'],
    nearbyAreas: ['Kingsport', 'Johnson City', 'Abingdon', 'Blountville'],
    primaryKeyword: 'plumber bristol tn',
    emergencyKeyword: 'emergency plumber bristol tn',
    drainKeyword: 'drain cleaning bristol tn',
    waterHeaterKeyword: 'water heater installation bristol tn',
    burstPipeKeyword: 'burst pipe repair bristol tn',
    pipeRepairKeyword: 'pipe repair bristol tn',
    avgResponseTime: '65 minutes',
    heroTagline: 'Bristol TN\'s Licensed Plumber',
    heroSub: 'The State Line City. Tennessee-Licensed Plumbing Available 24/7.',
    localFact: 'Bristol sits on the Tennessee-Virginia state line and is known as the Birthplace of Country Music. Our Tennessee-licensed plumbers serve all of the Bristol, TN side, covering homes and businesses throughout Sullivan County with emergency and scheduled plumbing services.',
  },
  {
    slug: 'morristown',
    name: 'Morristown',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Hamblen County',
    population: '30,000',
    zipCodes: ['37813', '37814', '37816'],
    nearbyAreas: ['Knoxville', 'Jefferson City', 'Greeneville', 'New Market'],
    primaryKeyword: 'plumber morristown tn',
    emergencyKeyword: 'emergency plumber morristown tn',
    drainKeyword: 'drain cleaning morristown tn',
    waterHeaterKeyword: 'water heater installation morristown tn',
    burstPipeKeyword: 'burst pipe repair morristown tn',
    pipeRepairKeyword: 'pipe repair morristown tn',
    avgResponseTime: '55 minutes',
    heroTagline: 'Morristown TN\'s Licensed Plumber',
    heroSub: 'Hamblen County\'s Dependable Plumbing Team. Available 24/7.',
    localFact: 'Morristown is the county seat of Hamblen County in Northeast Tennessee. The city\'s strong manufacturing base and established neighborhoods create consistent plumbing demand for both residential and light commercial properties throughout the area.',
  },
  {
    slug: 'hixson',
    name: 'Hixson',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Hamilton County',
    population: '40,000',
    zipCodes: ['37343'],
    nearbyAreas: ['Chattanooga', 'Soddy-Daisy', 'Sale Creek', 'Signal Mountain'],
    primaryKeyword: 'plumber hixson tn',
    emergencyKeyword: 'emergency plumber hixson tn',
    drainKeyword: 'drain cleaning hixson tn',
    waterHeaterKeyword: 'water heater installation hixson tn',
    burstPipeKeyword: 'burst pipe repair hixson tn',
    pipeRepairKeyword: 'pipe repair hixson tn',
    avgResponseTime: '45 minutes',
    heroTagline: 'Hixson TN\'s Licensed Plumber',
    heroSub: 'North Chattanooga\'s Trusted Plumbing Team. Same-Day Emergency Service.',
    localFact: 'Hixson is a rapidly growing suburban community north of Chattanooga along the Tennessee River. New construction subdivisions and established lakefront homes create high demand for water heater installations, drain cleaning, and emergency plumbing throughout the area.',
  },
  {
    slug: 'shelbyville',
    name: 'Shelbyville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Bedford County',
    population: '22,000',
    zipCodes: ['37160'],
    nearbyAreas: ['Murfreesboro', 'Nashville', 'Tullahoma', 'Lewisburg'],
    primaryKeyword: 'plumber shelbyville tn',
    emergencyKeyword: 'emergency plumber shelbyville tn',
    drainKeyword: 'drain cleaning shelbyville tn',
    waterHeaterKeyword: 'water heater installation shelbyville tn',
    burstPipeKeyword: 'burst pipe repair shelbyville tn',
    pipeRepairKeyword: 'pipe repair shelbyville tn',
    avgResponseTime: '55 minutes',
    heroTagline: 'Shelbyville TN\'s Licensed Plumber',
    heroSub: 'Bedford County\'s Reliable Plumbing Service. Licensed & Insured.',
    localFact: 'Shelbyville is the county seat of Bedford County and famous as the home of the Tennessee Walking Horse. The city\'s mix of agricultural, residential, and small commercial properties keeps our licensed plumbers busy throughout the year.',
  },
  {
    slug: 'tullahoma',
    name: 'Tullahoma',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Coffee County',
    population: '20,000',
    zipCodes: ['37388'],
    nearbyAreas: ['Murfreesboro', 'Shelbyville', 'Winchester', 'Manchester'],
    primaryKeyword: 'plumber tullahoma tn',
    emergencyKeyword: 'emergency plumber tullahoma tn',
    drainKeyword: 'drain cleaning tullahoma tn',
    waterHeaterKeyword: 'water heater installation tullahoma tn',
    burstPipeKeyword: 'burst pipe repair tullahoma tn',
    pipeRepairKeyword: 'pipe repair tullahoma tn',
    avgResponseTime: '55 minutes',
    heroTagline: 'Tullahoma TN\'s Licensed Plumber',
    heroSub: 'Coffee County Plumbing Pros. Dependable Service When You Need It.',
    localFact: 'Tullahoma is home to Arnold Air Force Base and has a strong aerospace and defense industry presence. The military and civilian workforce create steady demand for reliable licensed plumbing throughout Coffee County.',
  },
  {
    slug: 'millington',
    name: 'Millington',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Shelby County',
    population: '12,000',
    zipCodes: ['38053'],
    nearbyAreas: ['Memphis', 'Bartlett', 'Atoka', 'Munford'],
    primaryKeyword: 'plumber millington tn',
    emergencyKeyword: 'emergency plumber millington tn',
    drainKeyword: 'drain cleaning millington tn',
    waterHeaterKeyword: 'water heater installation millington tn',
    burstPipeKeyword: 'burst pipe repair millington tn',
    pipeRepairKeyword: 'pipe repair millington tn',
    avgResponseTime: '40 minutes',
    heroTagline: 'Millington TN\'s Licensed Plumber',
    heroSub: 'North Shelby County\'s Trusted Plumbing Team. Military-Friendly Service.',
    localFact: 'Millington is home to Naval Air Station Mid-South and has a significant military and veteran community. Our licensed plumbers understand the needs of military families and provide fast, reliable service throughout the Millington area.',
  },
  {
    slug: 'elizabethton',
    name: 'Elizabethton',
    state: 'Tennessee',
    stateAbbr: 'TN',
    county: 'Carter County',
    population: '14,000',
    zipCodes: ['37643'],
    nearbyAreas: ['Johnson City', 'Kingsport', 'Bristol', 'Roan Mountain'],
    primaryKeyword: 'plumber elizabethton tn',
    emergencyKeyword: 'emergency plumber elizabethton tn',
    drainKeyword: 'drain cleaning elizabethton tn',
    waterHeaterKeyword: 'water heater installation elizabethton tn',
    burstPipeKeyword: 'burst pipe repair elizabethton tn',
    pipeRepairKeyword: 'pipe repair elizabethton tn',
    avgResponseTime: '65 minutes',
    heroTagline: 'Elizabethton TN\'s Licensed Plumber',
    heroSub: 'Carter County\'s Dependable Plumbing Service. Available 24/7.',
    localFact: 'Elizabethton is a historic city in Carter County nestled in the beautiful mountains of Northeast Tennessee. The area\'s older home stock and cold mountain winters create consistent demand for pipe repairs, water heater replacements, and emergency plumbing services.',
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find(c => c.slug === slug);
}

export const CITY_SLUGS = CITIES.map(c => c.slug);
